### ISSUE TITLE
balanceadores problema al desencriptar tráfico https2

### ISSUE THREAD

**Issue by Raul-Martinez-e** [MUIT-RdDC-UAH-University/Ejemplo-2023-2024#1]
Estoy realizando la práctica de balanceadores de carga, en el punto 3 hay que entrar en el navegador del cliente y acceder a los web servers, pide observar que información se manda en las peticiones y respuestas, para ello estoy capturando el tráfico con wireshark desde el cliente y pese haber desencriptado: primero ejecutando el archivo append-sslkeys.sh que genera el archivo log_all_keys.log y luego metiendo este .log en el protocolo tls de wireshark, pero aún así no puedo ver el tráfico http2 entre cliente y servidor. He seguido todos los pasos que pone en la práctica y probado distintas cosas pero no he conseguido ver el tráfico desencriptado. ¿Qué solución se le ocurre?
Supuestamente he seguido todos los pasos para desencriptar pero aún así parece que no lo he conseguido ya que no puedo ver nada de tráfico http2.

**Comment by imyelmo** [comment]
Raúl, no nos consta que nadie haya tenido problemas, entiendo que estáis cometiendo algún error al seguir los pasos indicados. ¿Qué cosas has probado o hecho? Si no detallas lo que has hecho es imposible acotar el problema.

**Comment by diegoLopezP** [comment]
Los pasos que deberías realizar para hacer la captura que te piden en el punto 3 de la práctica, son los siguientes:

1. Inicias la captura de tráfico en el/los contenedores en los que quieres capturar el tráfico.
2. Abres el navegador Firefox del contenedor cliente.
3. En el navegador que acabas de abrir, borras el historial y la caché del navegador, por si los contenidos estuviesen guardados en la caché del navegador y no lanzase la petición.
4. En la barra de búsqueda del navegador, introduces la dirección https://ip_contenedor_al_que quieres hacer la petición. Véase la importancia de escribir **https** y no http, porque http2 utiliza, por defecto, https.
5. Una vez que el navegador ha mostrado la página web solicitada, se detienen las capturas de Wireshark.
6. En tu ordenador, ejecutas el script append-sslkeys.sh con permisos de sudo (sudo ./append-sslkeys.sh).
7. Compruebas que el fichero log_all_keys.log se ha modificado tras ejecutar el script del punto 6).
8. Añades el fichero log_all_keys.log a Wiresak, dentro del menú TLS.
9. Abres la captura que deseas con Wireshark, y filtras por tráfico http2.
10. El tráfico http2 intercambiado entre el contenedor cliente y el contenedor servidor web debería aparecer.
