### ISSUE TITLE
Fallo al tratar de levantar el servicio Vrrp en los balanceadores de carga 

### ISSUE THREAD

**Issue by victor-ramos-j** [MUIT-RdDC-UAH-University/Ejemplo-2023-2024#4]
No consigo levantar el servicio vrrp de forma correcta para redirigirlo a los servidores al realizar una petición a la ip virtual, configurada con la ip 192.168.2.2 en los archivos keepalived.conf , dentro de la carpeta keepalive.

Al intentar realizar el servicio de vrrp tampoco  consigo realizar las peticiones a los balanceadores, que antes si funcionaban correctamente y me reenviaban  a los servidores.

[Proyecto2.zip](https://github.com/MUIT-RdDC-UAH-University/Ejemplo-2023-2024/files/15387791/Proyecto2.zip)

**Comment by imyelmo** [comment]
Victor, subir las cosas al github, es subir las cosas a vuestro repositorio como corresponde: https://github.com/MUIT-RdDC-UAH-University/ProyectoGrupo2. Crear una carpeta específica aparte o una rama (branch) independiente, según creáis más conveniente.

**Comment by imyelmo** [comment]
En el docker compose estas llamando un fichero init.sh que no existe, hay uno que se llamar start.sh

El contenido del fichero start.sh, tendría que ser una única entrada según la estructura de directorios y PATHs existentes en el contenedor. Además, solo intentas arrancar el servicio de keepalive, no arrancas Caddy (también lo debería de incluir en el star.sh o init.sh, segun lo llames finalmente). Cuando arregles esto, ya subelo al GitHub correctamente.

**Comment by diegoLopezP** [comment]
Hola Victor,

Primer problema detectado. Desde el dockerfile del balanceador, en la orden CMD para el arranque del contenedor llamas al script "init.sh". Sin embargo, el script de arranque que tienes en el repositorio se llama "start.sh". Obviamente, nunca se va a ejecutar el script "init.sh" porque no existe (además, los volúmenes que tienes montados, también hacen la llamada a ese script "init.sh" que no existe. Comprueba por favor que se llama a este fichero correctamente.

Segundo problema detectado. En el script de arranque, además de Keepalive tienes que arrancar Caddy, por lo que tendrías que añadir una línea más para el arranque de caddy.

Como consejo, arranca una única instancia de Keepalive y comprueba que funciona correctamente el esquema master-slave. Una vez que ya funciona ese esquema, arranca la segunda instancia de Keepalive para probar el esquema master-master.

Como dice Isaías, sube al repositorio tus contribuciones, el trabajar con un .zip no es operativo. Si no quieres "fastidiar" la rama principal del repositorio, créate una branch en la que tengas un respaldo de las modificaciones que vas haciendo de tu parte.

Nos cuentas.

**Comment by imyelmo** [comment]
Por cierto, abrid la issue en vuestro propio repositorio
