### ISSUE TITLE
vrrp balanceadores de carga

### ISSUE THREAD

**Issue by Raul-Martinez-e** [MUIT-RdDC-UAH-University/Ejemplo-2023-2024#5]
Estoy realizando la configuración de vrrp para balanceadores de carga, pero al realizar un curl a la dirección ip virtual desde el cliente, obtengo la siguiente respuesta:
curl 192.168.3.100
curl: (7) Failed to connect to 192.168.3.100 port 80: No route to host
He arrancado caddy y keepalived y realizado su correspondiente configuración, la he subido a la rama rama_vrrp del repositorio de nuestro grupo. Pero no sé que puede estar fallando.

Una duda secundaria, el balanceo sin vrrp me funciona bien pero hay veces que uno de los balanceadores parece dejar de funcionar, ya que al realizar curl desde el cliente uno de los 2 responde con el error mencionado anteriormente. ¿A qué puede ser debido?

**Comment by diegoLopezP** [comment]
Hola Raúl,

Echando un vistazo rápido, los dos balaceadores, en su configuración de keepalive tienen la misma prioridad. Uno debería tener más prioridad que el otro para actuar como master-slave.

Para probar que vrrp funciona bien, cambia la configuración, para dar más prioridad a uno de los balanceadores. Después, los levantas y haces un ping desde el contenedor cliente a la IP virtual. Si el ping tiene respuesta, es que está funcionando vrrp.

Empezamos por ahí, y luego vemos la parte de balanceo de carga

**Comment by diegoLopezP** [comment]
Además, en el script de inicio start.sh, tienes que dejar keepalive ejecutándose en segundo plano, para ello, añade un & al final de la línea donde arrancas keepalive

**Comment by imyelmo** [comment]
Por cierto, si el problema persiste, abrid la issue en vuestro propio repositorio, no en el general.
