### ISSUE TITLE
Duda sobre las peticiones https

### ISSUE THREAD

**Issue by sergio-olmosc** [MUIT-RdDC-UAH-University/Ejemplo-2023-2024#6]
He añadido los certificados creados mediante el cliente a los servidores webs que escuchan por el 4443 y estos si responden correctamente al comando curl -k https://192.168.4.14:4443. (Debo poner el flag -k para que se muestre porque sino indica que los certificados al ser locales no le sirve.) 
En cambio, a la hora de realizar el curl bien a un balanceador o bien a la dirección VIP, no me muestra ningun error pero el contenido que devuelve es 0 y no sé si el problema está en el uso de los certificados o en la configuración del balanceador que provoque un mal balanceo.

**Comment by imyelmo** [comment]
@sergio-olmosc Abré la issue en el repositorio del proyecto de tu grupo, porque esto es algo muy concreto. Les pasaba a vosotros o a unos compañeros vuestros algo muy parecido el otro día. Si mal no recuerdo, el servidor devolvía las respuestas de tamaña 0. Quizás sea problema del servidor, tienes que captura tráfico para ver que esta pasando. Con lo que sea abre la issue donde corresonde como he dicho antes.
